In [2]:
import pandas as pd
import numpy as np
import sys
import os
from scipy import stats

# Add project root to path
sys.path.append(os.path.abspath(os.path.join('..')))

import util
import plotting.plotting_style as plt
from plotting.plotting_style import rgb

# Load Data
# file_path = '../../data_csv/final_Data_iaaf_scores_neu.csv'
df = util.load_data()

In [10]:
df[(df['disziplin'] == '100 m') & (df['jahr'] == 2025) & (df['altersklasse'] == 'Maenner')]

,jahr,geschlecht,altersklasse,disziplin,leistung,wind,name,geburtsjahr,verein,datum,ort,iaaf_score,group
236895,2025,M,Maenner,100 m,10.00,1.2,Lucas Ansah-Peprah,2000,Hamburger SV,14.06.2025,Regensburg,1206,Sprint
236896,2025,M,Maenner,100 m,10.05,1.1,Yannick Wolf,2000,Cologne Athletics,14.06.2025,Regensburg,1189,Sprint
236897,2025,M,Maenner,100 m,10.11,1.0,Owen Ansah,2000,Hamburger SV,10.08.2025,Rhede,1169,Sprint
236898,2025,M,Maenner,100 m,10.11,0.5,Heiko Gussmann,2004,Sprintteam Wetzlar,15.08.2025,Sondershausen,1169,Sprint
236899,2025,M,Maenner,100 m,10.13,1.8,Joshua Hartmann,1999,ASV Koeln e. V.,26.04.2025,Clermont FL (USA),1162,Sprint
236900,2025,M,Maenner,100 m,10.13,0.6,Kevin Kranz,1998,Sprintteam Wetzlar,14.06.2025,Regensburg,1162,Sprint
236901,2025,M,Maenner,100 m,10.18,1.4,Julian Wagner,1998,TV Wattenscheid 01,21.06.2025,Dessau-Rosslau,1145,Sprint
236902,2025,M,Maenner,100 m,10.19,0.9,Chidiera Onuoha,2003,ASV Koeln e. V.,15.08.2025,Sondershausen,1142,Sprint
236903,2025,M,Maenner,100 m,10.20,0.9,Marvin Schulte,1999,ASV Koeln e. V.,12.07.2025,Kortrijk (BEL),1138,Sprint
236904,2025,M,Maenner,100 m,10.22,-0.6,Deniz Almas,1997,LG Olympia Dortmund,02.08.2025,Dresden,1132,Sprint
236905,2025,M,Maenner,100 m,10.22,0.9,Aleksandar Askovic,1997,LG Stadtwerke Muenchen,15.08.2025,Sondershausen,1132,Sprint
236906,2025,M,Maenner,100 m,10.24,1.0,Benedikt Thomas Wallstein,2005,LAC Erdgas Chemnitz,10.08.2025,Rhede,1125,Sprint
236907,2025,M,Maenner,100 m,10.25,0.6,Fabian Olbert,2001,LG Stadtwerke Muenchen,09.08.2025,Andorf (AUT),1122,Sprint
236908,2025,M,Maenner,100 m,10.28,0.6,Jan Eric Frehe,2003,LG Brillux Muenster,14.06.2025,Regensburg,1112,Sprint
236909,2025,M,Maenner,100 m,10.29,1.1,Emilio Gonzalez,2003,LT DSHS Koeln,14.06.2025,Regensburg,1108,Sprint
236910,2025,M,Maenner,100 m,10.31,1.4,Jakob Kemminer,2007,LAC Quelle Fuerth,28.06.2025,Mannheim,1102,Sprint
236911,2025,M,Maenner,100 m,10.32,0.9,Maurice Grahl,2003,TSV Bayer o4 Leverkusen,14.06.2025,Regensburg,1099,Sprint
236912,2025,M,Maenner,100 m,10.35,0.3,James Adebola,2002,SCC Berlin,02.08.2025,Dresden,1089,Sprint
236913,2025,M,Maenner,100 m,10.37,1.5,Ben Troester,2007,TSG Lennestadt,14.06.2025,Regensburg,1082,Sprint
236914,2025,M,Maenner,100 m,10.39,0.6,Milian Zirbus,2005,Hannover 96,14.06.2025,Regensburg,1076,Sprint
236915,2025,M,Maenner,100 m,10.43,1.0,Michael Bryan,1992,TV Wattenscheid 01,14.06.2025,Winter Garden FL (USA),1063,Sprint
236916,2025,M,Maenner,100 m,10.43,0.5,Niklas Haaker,2002,LG Neustadt Nord,27.06.2025,Osterode,1063,Sprint
236917,2025,M,Maenner,100 m,10.43,0.3,Jonas Huegen,1994,LG Stadtwerke Muenchen,02.08.2025,Dresden,1063,Sprint
236918,2025,M,Maenner,100 m,10.46,-1.0,Manuel Eitel,1997,SSV Ulm 1846,31.05.2025,Goetzis (AUT),1053,Sprint
236919,2025,M,Maenner,100 m,10.46,1.5,Mika Dedekind,2007,LC Jena,07.06.2025,Berlin-Lichterfelde,1053,Sprint
236920,2025,M,Maenner,100 m,10.46,0.3,Eddie Reddemann,2003,TSV Bayer o4 Leverkusen,02.08.2025,Dresden,1053,Sprint
236921,2025,M,Maenner,100 m,10.47,0.1,Kevin Ugo,1995,TV Wattenscheid 01,31.05.2025,Krefeld,1050,Sprint
236922,2025,M,Maenner,100 m,10.47,1.1,Paul Erdle,2001,Hamburger SV,14.06.2025,Regensburg,1050,Sprint
236923,2025,M,Maenner,100 m,10.47,0.5,Pascal Kirstges,1997,LG Rhein-Wied,05.07.2025,Wetzlar,1050,Sprint
236924,2025,M,Maenner,100 m,10.47,0.9,Noah Olabisi,2003,SV Werder Bremen,05.07.2025,Ulm,1050,Sprint
236925,2025,M,Maenner,100 m,10.49,0.8,Felix Fruehn,2001,LT DSHS Koeln,24.05.2025,Weinheim,1043,Sprint
236926,2025,M,Maenner,100 m,10.49,1.2,Ivo Ziebold,2004,Dresdner SC 1898,14.06.2025,Regensburg,1043,Sprint
236927,2025,M,Maenner,100 m,10.49,0.9,Daniel Schwab,2003,LG Stadtwerke Muenchen,14.06.2025,Regensburg,1043,Sprint
236928,2025,M,Maenner,100 m,10.49,1.1,Justin Rennert,2005,SC Berlin,05.07.2025,Ulm,1043,Sprint
236929,2025,M,Maenner,100 m,10.50,1.9,Niclas Trabitzsch,1998,USC Mainz,09.06.2025,Mannheim,1040,Sprint
236930,2025,M,Maenner,100 m,10.50,0.9,Tobias Morawietz,2003,VfL Wolfsburg,14.06.2025,Regensburg,1040,Sprint
236931,2025,M,Maenner,100 m,10.51,1.5,Felix Schulze,2006,Hamburger SV,14.06.2025,Regensburg,1037,Sprint
236932,2025,M,Maenner,100 m,10.51,1.4,Alvin Mawumba,2007,TV Wattenscheid 01,28.06.2025,Mannheim,1037,Sprint
236933,2025,M,Maenner,100 m,10.52,-0.0,Sebastian Hetzner,2008,LAC Passau,29.06.2025,Vaterstetten,1034,Sprint
236934,2025,M,Maenner,100 m,10.52,0.6,Lukas Kasusch,2006,LG Kindelsberg Kreuztal,12.07.2025,Bochum-Wattenscheid,1034,Sprint
236935,2025,M,Maenner,100 m,10.52,0.4,Gabriel Wusu,2001,LG Brillux Muenster,10.08.2025,Rhede,1034,Sprint
236936,2025,M,Maenner,100 m,10.53,1.2,Louis Schuster,2007,SG Motor Gohlis-Nord Leipzig,24.05.2025,Dresden,1031,Sprint
236937,2025,M,Maenner,100 m,10.53,0.7,Amadeus Graeber,2005,Eintracht Frankfurt,31.05.2025,Goetzis (AUT),1031,Sprint
236938,2025,M,Maenner,100 m,10.55,1.3,Max Husemann,2005,Eintracht Hildesheim,07.06.2025,Zeven,1024,Sprint
236939,2025,M,Maenner,100 m,10.55,0.4,Maximilian Achhammer,2005,LG Stadtwerke Muenchen,09.08.2025,Andorf (AUT),1024,Sprint
236940,2025,M,Maenner,100 m,10.55,0.4,Niklas Goerigk,2002,LG Aachen,10.08.2025,Rhede,1024,Sprint
236941,2025,M,Maenner,100 m,10.55,0.4,Mustaqeem Kiani,2001,TV Gladbeck 1912,10.08.2025,Rhede,1024,Sprint
236942,2025,M,Maenner,100 m,10.56,1.9,Nils Kessler,1995,LG OVAG Friedberg-Fauerbach,09.06.2025,Mannheim,1021,Sprint
236943,2025,M,Maenner,100 m,10.56,0.6,Enzo Kiess,2007,LAC Erdgas Chemnitz,12.07.2025,Bochum-Wattenscheid,1021,Sprint
236944,2025,M,Maenner,100 m,10.56,0.8,Fjare Lorin Zirbus,2007,LG Osterode,12.07.2025,Bochum-Wattenscheid,1021,Sprint
236945,2025,M,Maenner,100 m,10.56,-0.5,Enrico Guentert,1997,TV Engen,06.09.2025,Lausanne (SUI),1021,Sprint

In [2]:
df = pd.read_csv("Data.csv", sep=";") # sep angeben

df

,jahr,geschlecht,altersklasse,disziplin,leistung,wind,name,geburtsjahr,verein,datum,ort
0,2017,W,Frauen,100 m,"10,95","+1,3",Gina Lueckenkemper,1996,LG Olympia Dortmund,05.08.,London/GBR
1,2017,W,Frauen,100 m,"11,06","+1,8",Rebekka Haase,1993,LV 90 Erzgebirge,25.05.,Zeulenroda
2,2017,W,Frauen,100 m,"11,14","-0,2",Lisa Mayer,1996,Sprintteam Wetzlar,27.08.,Berlin
3,2017,W,Frauen,100 m,"11,24","+0,3",Tatjana Pinto,1992,LC Paderborn,15.07.,Ninove/BEL
4,2017,W,Frauen,100 m,"11,25","+1,9",Sina Mayer,1995,LAZ Zweibruecken,11.06.,Regensburg
...,...,...,...,...,...,...,...,...,...,...,...
211554,2023,M,14,Speerwurf,"40,64",NaN,Tizian Zoeger,2010,LAC Aschersleben,29.04.2023,Schoenebeck
211555,2023,M,14,Speerwurf,"40,48",NaN,Phil Matthias,2009,SV Halle,07.05.2023,Halle (Saale)
211556,2023,M,14,Speerwurf,"40,38",NaN,Laurin Steep,2009,MTV Dannenberg,16.09.2023,Fallersleben (Wolfsburg)
211557,2023,M,14,Speerwurf,"40,36",NaN,Rico Lange,2009,TSV Chemie Premnitz,02.09.2023,Berlin-Lichterfelde
211558,2023,M,14,Speerwurf,"40,30",NaN,Johann Fichtner,2009,SV Preussen Berlin,02.07.2023,Berlin-Hohenschoenhausen

In [ ]:
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218240 entries, 0 to 218239
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   jahr          218240 non-null  int64
 1   geschlecht    218240 non-null  object
 2   altersklasse  218240 non-null  object
 3   disziplin     218240 non-null  object
 4   leistung      218240 non-null  object
 5   wind          41406 non-null   object
 6   name          218240 non-null  object
 7   geburtsjahr   218240 non-null  int64
 8   verein        218240 non-null  object
 9   datum         218240 non-null  object
 10  ort           218240 non-null  object
dtypes: int64(2), object(9)
memory usage: 18.3+ MB

,jahr,geschlecht,altersklasse,disziplin,leistung,wind,name,geburtsjahr,verein,datum,ort
count,218240.000000,218240,218240,218240,218240,41406,218240,218240.000000,218240,218240,218240
unique,NaN,2,7,56,45849,83,38241,NaN,5240,1324,4119
top,NaN,M,20,Hochsprung,"1,72","0,0",TSV Bayer,NaN,TSV Bayer Leverkusen,09.06.,Berlin
freq,NaN,109538,43721,12992,595,5855,150,NaN,3592,2237,8050
mean,2012.486203,NaN,NaN,NaN,NaN,NaN,NaN,466.445038,NaN,NaN,NaN
std,6.843930,NaN,NaN,NaN,NaN,NaN,NaN,773.463865,NaN,NaN,NaN
min,2001.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN
25%,2007.000000,NaN,NaN,NaN,NaN,NaN,NaN,85.000000,NaN,NaN,NaN
50%,2012.000000,NaN,NaN,NaN,NaN,NaN,NaN,91.000000,NaN,NaN,NaN
75%,2018.000000,NaN,NaN,NaN,NaN,NaN,NaN,98.000000,NaN,NaN,NaN
max,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,2012.000000,NaN,NaN,NaN

In [ ]:
df[df.duplicated()]

,jahr,geschlecht,altersklasse,disziplin,leistung,wind,name,geburtsjahr,verein,datum,ort
2954,2001,M,Maenner,110 m Huerden,"14,42","-0,4","Maczey, Mike",72,MobilCom ZKW Kiel,22.07.,Bernhausen
2960,2001,M,Maenner,110 m Huerden,"14,42","-0,4","Maczey, Mike",72,MobilCom ZKW Kiel,22.07.,Bernhausen
171754,2019,M,20,Zehnkampf,5.958,NaN,Jonathan Scheffel,0,TSV Muehldorf,19.05.,Eggenfelden
171755,2019,M,20,Zehnkampf,5.958,NaN,Jonathan Scheffel,0,TSV Muehldorf,19.05.,Eggenfelden
173024,2019,W,18,3.000 m Bahngehen,"18:34,84",NaN,Antonia Block,5,SV Halle,11.05.,Falkensee
174815,2020,W,Frauen,Hochsprung,"1,72",NaN,Lina Schubert,2002,SWC Regensburg,18.07.2020,Regensburg
182670,2021,W,Frauen,Siebenkampf,6.316,NaN,Vanessa Grimm,1997,Koenigsteiner LV,30.05.2021,Goetzis (AUT)

In [ ]:
df.isna().sum()
(df == '').sum()

jahr            0
geschlecht      0
altersklasse    0
disziplin       0
leistung        0
wind            0
name            0
geburtsjahr     0
verein          0
datum           0
ort             0
dtype: int64

In [ ]:
df["disziplin"].unique()

measurement = {
    "time": ['100 m', '200 m', '400 m', '800 m', '1500 m', '3000 m', '5000 m',
        '10 km', 'Halbmarathon', 'Marathon', '100 km', '100 m Huerden',
        '400 m Huerden', '3000 m Hindernis', '5000 m Gehen', '10 km Gehen',
        '20 km Gehen', '1000 m', '110 m Huerden', '10000 m',
        '10000 m Bahngehen', '50 km Gehen', '5 km', '80 m Huerden',
        '3000 m Bahngehen', '300 m', '300 m Huerden', '2000 m Hindernis',
        '2000 m', '1500 m Hindernis', '50 km Strassengehen',
        '10000 m Gehen', '1.500 m', '3.000 m', '5.000 m',
        '10.000 m', '3.000 m Hindernis', '5.000 m Bahngehen', '1.000 m', '10.000 m Bahngehen', '3.000 m Bahngehen', '2.000 m Hindernis', '2.000 m',
        '1.500 m Hindernis', '5.000 M'],
    "meter": ['Hochsprung', 'Stabhochsprung', 'Weitsprung',
       'Dreisprung', 'Kugelstoss', 'Diskuswurf', 'Hammerwurf',
       'Speerwurf'],
    "points": ['Fuenfkampf', 'Siebenkampf', 'Zehnkampf']
}

array(['100 m', '200 m', '400 m', '800 m', '1500 m', '3000 m', '5000 m',
       '10 km', 'Halbmarathon', 'Marathon', '100 km', '100 m Huerden',
       '400 m Huerden', '3000 m Hindernis', '5000 m Gehen', '10 km Gehen',
       '20 km Gehen', 'Hochsprung', 'Stabhochsprung', 'Weitsprung',
       'Dreisprung', 'Kugelstoss', 'Diskuswurf', 'Hammerwurf',
       'Speerwurf', '1000 m', '110 m Huerden', '10000 m',
       '10000 m Bahngehen', '50 km Gehen', '5 km', '80 m Huerden',
       '3000 m Bahngehen', '300 m', '300 m Huerden', '2000 m Hindernis',
       '2000 m', '1500 m Hindernis', '50 km Strassengehen',
       '10000 m Gehen', 'Zehnkampf', '1.500 m', '3.000 m', '5.000 m',
       '10.000 m', '3.000 m Hindernis', 'Siebenkampf',
       '5.000 m Bahngehen', '1.000 m', '10.000 m Bahngehen', 'Fuenfkampf',
       '3.000 m Bahngehen', '2.000 m Hindernis', '2.000 m',
       '1.500 m Hindernis', '5.000 M'], dtype=object)

In [ ]:
df['leistung'] = df['leistung'].str.replace(',', '.', regex=False).astype(float)
# df['wind'] = df['wind'].str.replace(',', '.', regex=False).astype(float)

ValueError: could not convert string to float: '1:58.62'

In [ ]:
import re

# Deine Regex-Muster
# pattern_time_hms = r'^\d{1,2}:\d{2}:\d{2}$'       # HH:MM:SS
pattern_time_hms = r'^\d{1,2}(:\d{1,2}){1,2}(,\d{1,2})?$'
# pattern_time_ms = r'^\d{1,2}:\d{2},\d{1,2}$'       # MM:SS,mS
pattern_time_float = r'^\d{1,2},\d{1,2}$'
# pattern_time_mmss = r'^\d{1,2}:\d{1,2}$'    
# pattern_points = r'^\d{1,2}.\d{3}$'
pattern_points = r'^\d{1,3}([.,]\d+)?$'           # z.B. 11,24

# Kombiniertes Muster: eins der drei muss passen
combined_pattern = f'({pattern_time_hms})|({pattern_float})|({pattern_points})'

# Maske für nicht passende Werte
mask_invalid = ~df['leistung'].astype(str).str.match(combined_pattern)


# Alle nicht passenden Werte in eine Liste
invalid_values = df.loc[mask_invalid, 'leistung'].tolist()

invalid_values

[]

In [5]:
import re

# Deine Patterns als Dictionary
patterns = {
    "HH:MM:SS,mS": r'^\d{1,2}(:\d{1,2}){1,2}(,\d{1,2})?$',
    "AA,BB": r'^\d{1,2},\d{1,2}$',
    "Numeric": r'^(?:\d{3,4}|\d{1}[.,]\d{3})$'
}

# Dictionary für Ergebnisse
pattern_disciplines = {name: set() for name in patterns.keys()}
measurement_key = 'points'
print(MEASUREMENT_TYPE[measurement_key])

df_time_disciplines = df[df['disziplin'].isin(MEASUREMENT_TYPE[measurement_key])]

pattern_1 = False
pattern_2 = False
pattern_3 = False

# Über jede Zeile iterieren
for _, row in df_time_disciplines.iterrows():
    leistung = str(row['leistung'])
    disziplin = row['disziplin']
    
    for name, pattern in patterns.items():
        if re.match(pattern, leistung):
            if not pattern_1 and name == "HH:MM:SS,mS":
                print(leistung)
                pattern_1 = True
            if not pattern_2 and name == "AA,BB":
                print(leistung)
                pattern_2 = True
            if not pattern_3 and name == "Numeric":
                print(leistung)
                pattern_3 = True

            pattern_disciplines[name].add(disziplin)
            break  # wenn ein Pattern matched, nicht weiter prüfen

# Sets in Listen umwandeln
pattern_disciplines = {k: sorted(list(v)) for k, v in pattern_disciplines.items()}

disciplines = []

# Ergebnis anzeigen
for k, v in pattern_disciplines.items():
    print(f"{k}: {v}")
    disciplines.extend(v)

print(set(MEASUREMENT_TYPE[measurement_key]).difference(set(disciplines)))
print(sorted(disciplines) == sorted(MEASUREMENT_TYPE[measurement_key]))

['Siebenkampf', 'Zehnkampf']
6.319
HH:MM:SS,mS: []
AA,BB: []
Numeric: ['Siebenkampf', 'Zehnkampf']
set()
True

# Leistungsfehler (Leistung wird wg. Wind gekuerzt)

In [ ]:
import re
import pandas as pd

def fix_incomplete_leistung(df):
    # Maske: Leistung ist nur eine ganze Zahl (1–99) ohne Komma oder Doppelpunkt
    mask = df["leistung"].astype(str).str.fullmatch(r"\d{1,2}")

    # Kombinieren: leistung + wind (falls wind existiert)
    df.loc[mask & df["wind"].notna(), "leistung"] = (
        df.loc[mask, "leistung"].astype(str) + df.loc[mask, "wind"].astype(str)
    )

    # Wind auf None setzen
    df.loc[mask, "wind"] = None

    return df

df = fix_incomplete_leistung(df)
df

In [ ]:
df.to_csv("Data.csv", sep=";", index=False)

In [7]:
discipline_standardization = {
    # Läufe
    "60m": "60 m", "100m": "100 m", "200m": "200 m", "300m": "300 m",
    "400m": "400 m", "800m": "800 m", "1000m": "1000 m", "1500m": "1500 m",
    "3000m": "3000 m", "5000m": "5000 m", "10000m": "10 000 m",
    "5km": "5 km", "10km": "10 km", "20km": "20 km",
    "10 km Straßengehen": "10 km Gehen",
    "10 km Gehen": "10 km Gehen",
    "20 km Gehen": "20 km Gehen",
    "20 km Straßengehen": "20 km Gehen",
    "5000 m Bahngehen": "5000 m Gehen",
    "10 000 m Bahngehen": "10 000 m Gehen",

    # Hürden
    "100 m Hürden": "100 m Huerden", "110 m Hürden": "110 m Huerden", "400 m Hürden": "400 m Huerden",

    # Sprung / Wurf
    "Weitsprung": "Weitsprung", "Hochsprung": "Hochsprung", "Dreisprung": "Dreisprung",
    "Stabhochsprung": "Stabhochsprung", "Kugelstoß": "Kugelstoss", "Speerwurf": "Speerwurf",
    "Diskuswurf": "Diskuswurf", "Hammerwurf": "Hammerwurf",

    # Mehrkampf
    "Zehnkampf": "Zehnkampf", "Siebenkampf": "Siebenkampf"
}

a = set(df['disziplin'].unique())
b = set(discipline_standardization.values())
print(a)
print(b)
print(a.difference(b))
print(b.difference(a))

{'100 m Huerden', '3.000 m', '300 m', '5 km', '20 km Gehen', '400 m', '10000 m Gehen', 'Marathon', 'Dreisprung', '10000 m', '1.500 m', '3.000 m Bahngehen', '50 km Gehen', '5000 m', 'Hammerwurf', '2.000 m Hindernis', '5.000 m Bahngehen', '10.000 m', '1.500 m Hindernis', '1500 m Hindernis', '110 m Huerden', '5.000 m', 'Siebenkampf', '10.000 m Bahngehen', '100 m', '1.000 m', 'Weitsprung', '10000 m Bahngehen', 'Hochsprung', '10 km Gehen', '3000 m', '400 m Huerden', '10 km', '200 m', '1500 m', '800 m', '5000 m Gehen', '3000 m Hindernis', '1000 m', 'Kugelstoss', 'Diskuswurf', 'Speerwurf', '2000 m Hindernis', '2.000 m', 'Halbmarathon', 'Stabhochsprung', '3.000 m Hindernis', 'Zehnkampf', '100 km', '2000 m', '3000 m Bahngehen'}
{'100 m Huerden', '300 m', '5 km', '20 km Gehen', '400 m', 'Dreisprung', '5000 m', '60 m', 'Hammerwurf', '110 m Huerden', 'Siebenkampf', '100 m', 'Weitsprung', '20 km', 'Hochsprung', '10 km Gehen', '3000 m', '400 m Huerden', '10 km', '1000 m', '5000 m Gehen', '800 m', '200 m', '1500 m', 'Kugelstoss', 'Speerwurf', 'Diskuswurf', '10 000 m', 'Stabhochsprung', '10 000 m Gehen', 'Zehnkampf'}
{'3.000 m', '10000 m Gehen', 'Marathon', '10000 m', '1.500 m', '3.000 m Bahngehen', '50 km Gehen', '2.000 m Hindernis', '5.000 m Bahngehen', '10.000 m', '1.500 m Hindernis', '1500 m Hindernis', '5.000 m', '1.000 m', '10000 m Bahngehen', '3000 m Hindernis', '2000 m Hindernis', '2.000 m', 'Halbmarathon', '3.000 m Hindernis', '10.000 m Bahngehen', '100 km', '2000 m', '3000 m Bahngehen'}
{'60 m', '10 000 m Gehen', '10 000 m', '20 km'}

In [ ]:
def standardize_name(name):
    if ',' in name:
        last, first = name.split(',', 1)
        return f"{first.strip()} {last.strip()}"
    return name.strip()

df['name'] = df['name'].apply(standardize_name)
df

In [ ]:
def standardize_birthyear(year):
    if pd.isna(year):
        return None
    
    year = str(year).strip()  # in String umwandeln
    
    # Sonderfall: '0' → 2000
    if year == '0':
        return 2000
    
    # Vierstelliges Jahr, z.B. '2014'
    if len(year) == 4:
        return int(year)
    
    # Zweistelliges Jahr, z.B. '80', '98', '00', '01'
    if len(year) == 2:
        yy = int(year)
        if yy >= 50:        # alles >=50 → 1900er
            return 1900 + yy
        else:               # alles <50 → 2000er
            return 2000 + yy
    
    # Einstellige Zahl, z.B. '9' → 2009?
    if len(year) == 1:
        return 2000 + int(year)
    
    # Alles andere: zurückgeben als int, falls möglich
    try:
        return int(year)
    except:
        return None
    
# df['geburtsjahr'] = df['geburtsjahr'].apply(standardize_birthyear)
df['geburtsjahr'].unique()

array([  73,   70,   81,   78,   82,   72,   80,   75,   71,   79,   74,
         77,   83,   84,   85,   65,   67,   69,   86,   76,   66,   68,
         64,   60,   61,   62,   59,   63,   57,   56,   53,   55,   54,
         49,   43,   48,   52,   39,    5,   40,   42,   41,   51,   45,
         88,   87,   58,   50,   37,   46,   90,   44,   32,   35,   89,
         47,   36,   33,   91,   93,   92, 1860,   24,   94,   95,   96,
         97,    4,   98,    9,   99,    0,   29,    8,   38,    1,    2,
          3, 1861, 1845, 1881, 1912, 1846, 1884, 1898, 1847, 1885,    6,
       1893,    7, 1947, 1920, 1999, 1994, 1990, 1998, 1995, 2001, 2004,
       1997, 2003, 1991, 2000, 1996, 1985, 2002, 1993, 1992, 2005, 2006,
       1989, 1987, 1983, 1980, 1976, 1982, 1974, 1972, 1971, 1979, 1981,
       1963, 2007, 1969, 2008, 1986, 1978, 1988, 1977, 1973, 1968, 1984,
       1970, 1965, 1959, 1962, 1964, 1944, 1940, 1958, 1960, 1961, 1957,
       1966, 1939, 1952, 1975, 1955, 1967, 1954, 1949, 1951, 1953, 1942,
       1956, 1950, 1943, 2009, 1834, 1946, 2010, 1874, 1849, 1891, 1938,
       2011, 2012])

In [4]:
import re

line_pattern_01_17 = re.compile(
    r"^(?:([1-9]\d?|50)\s+)?"                        # optional Platz
    r"(?P<leistung>("
    r"\d{1,2},\d{1,2}|"                              # SS,S oder SS,SS
    r"\d{1,2}:\d{2},\d{2}|"                          # M:SS,SS
    r"\d{1,2}:\d{2}:\d{2}|"                          # H:MM:SS
    r"\d{1,2}:\d{2}|"                                # M:SS
    r"\d{1,5}(?:\.\d{3})?"                            # Punkte, z.B. 8307
    r"))\s*"                                         # Leistung
    # Wind: erlaubt (±x,x) oder ±x,x mit/ohne Leerzeichen
    r"(?:(?:\(?\s*(?P<wind>[+-]\d,\d)\s*\)?)\s+)?"
    r"(?P<name>[A-Za-zÄÖÜäöüß ,\-]+?)\s+"            # Name
    r"(?P<geburtsjahr>\d{2,4})\s+"                   # Geburtsjahr
    r"(?P<verein>[A-Za-zÄÖÜäöüß0-9 .\-()/]+)\s+"     # Verein
    r"(?P<datum>(?:\d{1,2}\./\d{1,2}\.\d{2}\.)|\d{2}\.\d{2}\.(?:\d{2,4})?)"             # Datum
    r"(?P<ort>[A-Za-zÄÖÜäöüß .\-()/]+)$"             # Ort
)

line_pattern_18_22 = re.compile(
    r"^(?:([1-9]\d?|50)\s+)?"                              # Platz optional
    r"(?P<leistung>("
        r"\d{1,2},\d{2}|"                                 # SS,SS
        r"\d{1,2}:\d{2},\d{2}|"                           # M:SS,SS
        r"\d{1,2}:\d{2}:\d{2}|"                           # H:MM:SS
        r"\d{1,2}:\d{2}|"                                 # M:SS
        r"\d{1,5}(?:\.\d{3})?"                            # Punkte, z.B. 8307
    r"))\s*"
    r"(?:(?:\(?\s*(?P<wind>[+-]?\d,[0-9])\s*\)?)\s+)?"     # Wind optional, auch mit ()
    r"(?P<name>[A-Za-zÄÖÜäöüß'´`\- ]+?)\s+"                # Name
    r"(?P<geburtsjahr>\d{2,4})\s+"                         # Geburtsjahr
    r"(?P<verein>[A-Za-zÄÖÜäöüß0-9 .\-()/]+?)\s+"          # Verein
    r"(?P<datum>\d{2}\.\d{2}(?:\.\d{2,4})?)\.?\s+"         # HIER IST DIE KORREKTUR: \.? hinzugefügt
    r"(?P<ort>[A-Za-zÄÖÜäöüß .\-()/]+)$",                  # Ort
    re.UNICODE
)


line = '8545 Niklas Kaul 1998 USC Mainz 16.08.2022 München'
m = line_pattern_18_22.match(line)
print("Match:", bool(m))
if m:
    print(m.groupdict())

Match: True
{'leistung': '8545', 'wind': None, 'name': 'Niklas Kaul', 'geburtsjahr': '1998', 'verein': 'USC Mainz', 'datum': '16.08.2022', 'ort': 'München'}

In [ ]:
import re

lauf_pattern = (
    r"("
    r"10\s?km Straßengehen|20\s?km Straßengehen|50\s?km Straßengehen|"
    r"(?:10|20|50)\s?km\s?Gehen|(?:10|20|50)\s?k\s?Gehen|"
    r"(?:5|10|20|50|100)\s?km|"
    r"(?:1[ .]?000|1[ .]?500|2[ .]?000|3[ .]?000|5[ .]?000|10[ .]?000)\s?m\s?(?:Bahngehen|Gehen|Hindernis|Hürden)?|"
    r"(?:60|80|100|110|200|300|400|800|1000|1500|2000|3000|5000|10000)\s?m\s?(?:Hindernis|Hürden)?|"
    r"^(60|80|100|110|200|300|400|800|1000|1500|2000|3000|5000|10000)\s*[\u00A0\u202F]?\s*m\b|"
    r"Halbmarathon|Marathon"
    r")"
)

discipline_pattern = re.compile(
    r"^("
    + lauf_pattern + "|" +
    r"Weitsprung|Hochsprung|Dreisprung|Stabhochsprung|"
    r"Kugelstoß|Speerwurf|Diskuswurf|Hammerwurf|"
    r"Zehnkampf|Siebenkampf|Fünfkampf|10-Kampf|7-Kampf|5-Kampf"
    r")"
)

print(discipline_pattern.match('1000 m Bahngehen'))  # ✅ Match

<re.Match object; span=(0, 16), match='1000 m Bahngehen'>

In [ ]:
measurement_types = MEASUREMENT_TYPE

discipline = 'Speerwurf'

def get_measurement_key(discipline, measurement_types):
    for key, values in measurement_types.items():
        if discipline in values:
            return key
    return None   # falls nicht gefunden

key = get_measurement_key(discipline, measurement_types)
print(key)  # Ausgabe: 'time'

meter

In [1]:
import re

pattern = r"(?P<datum>(?:\d{1,2}\./\d{1,2}\.\d{2}\.)|\d{2}\.\d{2}\.(?:\d{2,4})?)"

test = ['06./07.08.']

for t in test:
    print(t, re.match(pattern, t))

06./07.08. <re.Match object; span=(0, 10), match='06./07.08.'>